# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    # valid drivers options include "gd" or "gmagick" or "imagick"
    driver: "gd"

    filter_sets:
        # name our filter set "my_thumb_filter"
        squared_thumbnail_medium:
            filters:
                thumbnail:
                    # set the thumbnail size to "300x300" pixels
                    size: [400, 400]
                    # crop the input image, if required
                    mode: outbound
                    allow_upscale: true

        squared_thumbnail_small:
            filters:
                thumbnail:
                    size: [50, 50]
                    mode: outbound
                    allow_upscale: true
