vich_uploader:
    db_driver: orm

    mappings:
        image_name:
            uri_prefix: /images/aliments
            upload_destination: '%kernel.project_dir%/public/images/aliments'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
